---
abstract: 'Perl extension to aid in eliminating globals'
author:
  - 'Stephen Nelson <stephenenelson@mac.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Devel-WarnGlobal
requires:
  Carp: 0
  strict: 0
  vars: 0
  warnings: 0
version: 0.07
